version: "2"

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck

formatters:
  enable:
    - gofumpt
    - goimports
